[build-system]
requires = ['setuptools>=61', 'setuptools_scm>=6.2']
build-backend = "setuptools.build_meta"

[project]
name = "tw-api"
version = "0.1.0"
authors = [{name = "vladkens"}]
description = "Twitter GraphQL and Search API implementation with SNScrape data models"
readme = "readme.md"
requires-python = ">=3.10"
keywords = ["twitter", "api", "scrape", "snscrape", "tw-api", "twapi"]
license = {text = "MIT"}
classifiers = [
	'Development Status :: 4 - Beta',
	'License :: OSI Approved :: MIT License',
	'Programming Language :: Python :: 3.10',
	'Programming Language :: Python :: 3.11',
]
dependencies = [
  "fake-useragent==1.1.3",
  "httpx==0.24.0",
  "loguru==0.7.0"
]

[project.optional-dependencies]
dev = [
  "pylint==2.17.3",
  "pytest-asyncio==0.21.0",
  "pytest-cov==4.0.0",
  "pytest==7.3.1",
  "ruff==0.0.263",
]

[project.urls]
repository = "https://github.com/vladkens/tw-api"

[tool.setuptools]
packages = ['twapi']

[tool.pytest.ini_options]
pythonpath = ["."]
asyncio_mode = "auto"

[tool.isort]
profile = "black"

[tool.black]
line-length = 99

[tool.ruff]
line-length = 99
