name: ci

on: [push]

env:
  PIP_ROOT_USER_ACTION: ignore

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --quiet -r requirements.txt
          pip install --quiet -r requirements-dev.txt

      - name: lint
        run: make lint
      
      - name: test
        run: make test
